### ISSUE TITLE
explore 3 template designs

### ISSUE THREAD

**Issue by MadBananaUnionDAO** [MadBananaUnion-DAO/madbananaunion.com#2]

**Comment by MadBananaUnionDAO** [comment]
Lets explore 3 different designs of html and css so we may dial in how our site will look

**Comment by mon-key-mike** [comment]
We can use this project Management flow to take notes

**Comment by Bigtime001** [comment]
Hello !
I just saw your email, can you text me on discord?

**Comment by Bigtime001** [comment]
Alright 
We'd start with the header let me show some samples

**Comment by mon-key-mike** [comment]
Current design is the template moving forward, design will change further from here, but this issue will be closed and we will move into the next 3 designs . well go 3 designs, to iterate in sequence as we add features

**Comment by mon-key-mike** [comment]
button clicking logger and signup / auth is next.
